language: node_js

node_js:
  - 0.10
  - 0.12

# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
  # GUI for real browsers.
  - npm install -g npm


